name: Publish to GitHub Pages
on:
  push:
    branches:
      - main # Set a branch name to trigger the workflow on pushes to this branch
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Use a stable version of Node.js
      - name: Install Dependencies
        run: npm install
      - name: Build Site
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: .
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.homebakecakes}}
          publish_dir: ./build # Specify the output directory of your built site
